app/controllers/main.py
#!/usr/bin/python
# coding=utf-8
# -------------------------------------------------------------
#       LB2 Mail Migration
#
#       Autor: Tiago M Reichert
#       Data Inicio:  20/04/2017
#       Data Release:
#       email: tiago.miguel@lb2.com.br
#       Versão: v1.0a
#       LB2 Consultoria - Leading Business 2 the Next Level!
# --------------------------------------------------------------

from flask import render_template, request, Blueprint, redirect, url_for, flash, make_response
from app.models import db, Message, Account, Server, Status, Company, Migration
from datetime import datetime
from app.utils import authentication

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('Index.html')


@main.route('/create_client', methods=['GET', 'POST'])
@authentication.admin.login_required
def create_client():
    if request.method == 'GET':
        return render_template('CreateClient.html')
    elif request.method == 'POST':
        c = Company(name=request.form['name'], contact_number=request.form['contact_number'], contact_name=request.form['contact_name'], cnpj=request.form['cnpj'])
        db.session.add(c)
        db.session.commit()
        return render_template('Index.html')


@main.route('/create_server', methods=['GET', 'POST'])
@authentication.admin.login_required
def create_server():
    if request.method == 'GET':
        return render_template('CreateServer.html')
    elif request.method == 'POST':
        if request.form.get('ssl'):
            s = Server(desc=request.form['desc'], address=request.form['address'], ssl=True,
                       type=request.form['type'], port=request.form['port'])
        else:
            s = Server(desc=request.form['desc'], address=request.form['address'], ssl=False,
                       type=request.form['type'], port=request.form['port'])
        db.session.add(s)
        db.session.commit()
        return render_template('Index.html')


@main.route('/migrations', methods=['GET', 'POST'])
@authentication.admin.login_required
def migrations():
    if request.method == 'GET':
        return render_template('Migrations.html', company=Company, existing_migrations=Migration.query.all(), clientes=Company.query.all())
    elif request.method == 'POST':
        company = request.form['company']
        start_time = datetime.now().strftime("%d/%m/%Y %H:%M")
        m = Migration(company_id=company, start_date=start_time)
        db.session.add(m)
        db.session.commit()
        return render_template('Migrations.html', company=Company, existing_migrations=Migration.query.all(),
                               clientes=Company.query.all())


@main.route('/config/<migration_id>', methods=['PUT', 'GET', 'POST'])
@authentication.admin.login_required
def config_migration(migration_id):
    if request.method == 'POST':
        if 'put' in request.form['_method']:
            account_list = request.files['account_list']
            lista_contas = account_list.read()
            read_error_lines = None
            for linha in str(lista_contas).split('\n'):
                try:
                    if linha != '':
                        colunas = linha.split(',')
                        print colunas
                        src_server_id = colunas[0]
                        email = colunas[1]
                        src_password = colunas[2]
                        dst_password = colunas[3]
                        account = Account(src_server_id=src_server_id, migration_id=migration_id, src_email=email,
                                          src_password=src_password, dst_email=email, dst_password=dst_password,
                                          status_id=1)
                        db.session.add(account)
                        db.session.commit()

                except:
                    read_error_lines = linha+'\n'
            if read_error_lines is not None:
                response = make_response(read_error_lines)
                response.headers["Content-Disposition"] = "attachment; filename=CONTAS_EMAIL_INVALIDAS.txt"
                return response

        else:
            src_server_id = request.form['src_server_id']
            src_email = request.form['src_email']
            src_password = request.form['src_password']
            dst_email = request.form['tgt_email']
            dst_password = request.form['tgt_password']
            account = Account(src_server_id=src_server_id, migration_id=migration_id, src_email=src_email,
                              src_password=src_password, dst_email=dst_email, dst_password=dst_password, status_id=1)
            db.session.add(account)
            db.session.commit()

    c = Company.query.filter_by(id=(Migration.query.filter_by(id=migration_id).first().company_id)).first(),
    acc = Account.query.filter_by(migration_id=migration_id).all()
    return render_template('Configuration.html', cliente=c,
    accounts=acc, servers=Server.query.all(), server=Server, status=Status, message=Message)


@main.route('/config/<migration_id>/remove/<account_id>', methods=['GET'])
@authentication.admin.login_required
def remove_migration(migration_id, account_id):
    Account.query.filter_by(id=account_id).delete()
    db.session.commit()
    return redirect(url_for('main.config_migration', migration_id=migration_id))


@main.route('/config/<migration_id>/reanalyze/<account_id>', methods=['GET'])
@authentication.admin.login_required
def reanalyze_migration(migration_id, account_id):

    Account.query.filter_by(id=account_id).update({'status_id': 1})
    db.session.commit()
    return redirect(url_for('main.config_migration', migration_id=migration_id))

app/templates/Configuration.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ STATIC_URL }}/static/img/logo.png" />
    <title>LB2 Email Migration</title>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/jquery-3.1.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/bootstrap.min.js"></script>
    <link href="{{ STATIC_URL }}/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('main.index')}}">LB2 - Email Migration</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.migrations')}}">Configurar Migração</a></li>
            <li><a href="{{ url_for('main.create_client')}}">Adicionar Cliente</a></li>
            <li><a href="{{ url_for('main.create_server')}}">Adicionar Servidor</a></li>        </ul>
    </div>
</nav>
<div class="flashes">
    {% for message in get_flashed_messages()%}
        <h4 class="form-text text-muted text-danger text-center">{{ message }}</h4>
    {% endfor %}
</div>

<div class="col-sm-3"><br>
<button type="button" class="btn btn-success btn-md pull-right" data-toggle="modal" data-target="#importModal">Importar Contas de Lista</button>
  <!-- Modal -->
  <div class="modal fade" id="importModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Importar Contas de Lista</h4>
        </div>
        <div class="modal-body">
            <form action = "{{ request.path }}" method="post" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="put" />
                <div class="form-group">
                    <label>Lista:</label>
                    <input type="file"  class="form-control" required="true" name="account_list" placeholder="Lista de Contas de Email"/>
                    <small class="form-text text-muted">Fazer upload da lista de contas de email</small>
                </div>
                <input type = "submit" class="btn btn-info btn-md center-block" value = "Enviar" />
            </form>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
</div>

<form class="form-inline" action = "{{ request.path }}" method="get" enctype="multipart/form-data">
    <div class="col-sm-8"><br>
        <input type = "submit" class="btn btn-warning btn-md pull-right" value = "Atualizar Página" />
    </div>
</form>
<br><br><br><br>
<h4><div style="display: inline" class="col-sm-offset-1 text-info">Adicionar Conta na Migração do Cliente:</div><div style="display: inline" class="text-warning"> {{ cliente.name }}</div></h4>
<div class="col-sm-12 text-center" >
    <form class="form-inline" action = "{{ request.path }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="post" />
        <div class="form-group">
            <label>Origem:</label>
            <select required="true" class="form-control" name="src_server_id">
                    {% for s in servers %}
                        <option value="{{ s.id }}">{{ s.desc }}</option>
                    {% endfor %}
            </select>
            <input type="text" class="form-control" required="true" name="src_email" placeholder="Email"/>
            <input type="text" class="form-control" required="true" name="src_password" placeholder="Senha"/>&nbsp;&nbsp;&nbsp;&nbsp;
            <label>Destino:</label>
            <input type="text" class="form-control" required="true" name="tgt_email" placeholder="Email"/>
            <input type="text" class="form-control" required="true" name="tgt_password" placeholder="Senha"/>
        </div>
        <div class="col-sm-12"><br>
        <input type = "submit" class="btn btn-info btn-md center-block" value = "Adicionar" />
        </div>
    </form>

</div>

{% if accounts %}
<div class="col-sm-offset-1 text-info"><h4>Migrações Adicionadas</h4></div>
    <div class="table-responsive col-sm-offset-1 col-sm-10">
        <table class="table table-striped table-bordered table-hover">
            <thead class="text-warning">
            <th class="text-center">ID</th>
            <th class="text-center">Servidor de Origem</th>
            <th class="text-center">Email de Origem</th>
            <th class="text-center">Email de Destino</th>
            <th class="text-center">Status</th>
            <th class="text-center">Migradas</th>
            <th class="text-center">Total</th>
            <th class="text-center">Sem UID</th>
            <th class="text-center">Duplicadas</th>
            <th class="text-center">Percentual</th>
            <th class="text-center">Remover</th>
            <th class="text-center">Reanalisar</th>
            </thead>
            <tbody>
            {% for accs in accounts %}
                <tr>
                    <td class="text-center">{{ accs.id }}</td>
                    <td class="text-center">{{ server.query.filter_by(id=accs.src_server_id).first().desc }}</td>
                    <td class="text-center">{{ accs.src_email }}</td>
                    <td class="text-center">{{ accs.dst_email }}</td>
                    <td class="text-center">{{ status.query.filter_by(id=accs.status_id).first().description }}</td>
                    <td class="text-center">{{ message.query.filter_by(account_id=accs.id).count() }}</td>
                    <td class="text-center">{% if accs.qtd_message != None %}{{accs.qtd_message}}{% else %}Não Calculado{% endif %}</td>
                    <td class="text-center">{% if accs.without_messageid != None %} {{accs.without_messageid}}{% else %}Não Calculado{% endif %}</td>
                    <td class="text-center">{% if accs.duplicates != None %} {{accs.duplicates}}{% else %}Não Calculado{% endif %}</td>
                    <td class="text-center">{% if accs.qtd_message and accs.duplicates != None %}{{'%0.2f' %(((message.query.filter_by(account_id=accs.id).count()+accs.duplicates)/(accs.qtd_message))*100) }}%{% else %}Não Calculado{% endif %} </td>
                    <td class="text-center">
                        {% if message.query.filter_by(account_id=accs.id).count()  == 0 %}
                            <form action = "{{ request.path }}/remove/{{ accs.id }}" method="get">
                                <input type = "submit" class="btn btn-danger btn-md center-block btn" value = "Excluir" />
                            </form>
                        {% else %}
                         <input type = "submit" class="btn btn-danger btn-md center-block btn disabled" value = "Excluir" />
                        {% endif %}
                    </td>
                    <td class="text-center">
                        {% if accs.status_id  < 3 %}
                            <input type = "submit" class="btn btn-success btn-md center-block btn disabled" value = "Reanalisar" />
                        {% else %}
                            <form action = "{{ request.path }}/reanalyze/{{ accs.id }}" method="get">
                                <input type = "submit" class="btn btn-success btn-md center-block btn" value = "Reanalisar" />
                            </form>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

</body>
</html>

app/templates/CreateClient.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ STATIC_URL }}/static/img/logo.png" />
    <title>LB2 Email Migration</title>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/jquery-3.1.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/bootstrap.min.js"></script>
    <link href="{{ STATIC_URL }}/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('main.index')}}">LB2 - Email Migration</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.migrations')}}">Configurar Migração</a></li>
            <li><a href="{{ url_for('main.create_client')}}">Adicionar Cliente</a></li>
            <li><a href="{{ url_for('main.create_server')}}">Adicionar Servidor</a></li>
        </ul>
    </div>
</nav>
<br>
<div class="flashes">
    {% for message in get_flashed_messages()%}
        <h4 class="form-text text-muted text-danger text-center">{{ message }}</h4>
    {% endfor %}
</div>

<div class="col-sm-offset-4 col-sm-12 text-center" >
    <form class="form-group col-lg-4" action = "{{ request.path }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="post" />
        <div class="form-group">
            <br>
            <label>Dados do Cliente</label><br><br>
            <input type="text" class="form-control input-normal" required="true" name="name" placeholder="Nome da Empresa"/><br>
            <input type="text" class="form-control" name="contact_number" placeholder="Numero para Contato"/><br>
            <input type="text" class="form-control"  name="contact_name" placeholder="Nome do Contato"/><br>
            <input type="text" class="form-control"  name="cnpj" placeholder="CNPJ"/>
        </div>
        <div class="col-sm-12"><br>
        <input type = "submit" class="btn btn-info btn-md center-block" value = "Adicionar" />
        </div>
    </form>

</div>

</body>
</html>

app/templates/CreateServer.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ STATIC_URL }}/static/img/logo.png" />
    <title>LB2 Email Migration</title>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/jquery-3.1.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/bootstrap.min.js"></script>
    <link href="{{ STATIC_URL }}/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('main.index')}}">LB2 - Email Migration</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.migrations')}}">Configurar Migração</a></li>
            <li><a href="{{ url_for('main.create_client')}}">Adicionar Cliente</a></li>
            <li><a href="{{ url_for('main.create_server')}}">Adicionar Servidor</a></li>
        </ul>
    </div>
</nav>
<br>
<div class="flashes">
    {% for message in get_flashed_messages()%}
        <h4 class="form-text text-muted text-danger text-center">{{ message }}</h4>
    {% endfor %}
</div>

<div class="col-sm-offset-4 col-sm-12 text-center" >
    <form class="form-group col-lg-4" action = "{{ request.path }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="post" />
        <div class="form-group">
            <br>
            <label>Dados do Servidor</label><br><br>
            <div class="col-lg-12 text-center" >
                <input type="text" class="text-center form-control input-normal" required="true" name="desc" placeholder="Nome do Servidor"/><br>
            </div>
            <div class="col-lg-6 text-center" >
                <input type="text" class="text-center form-control input-normal" required="true" name="address" placeholder="Endereço IP"/>
            </div>
            <div class="col-lg-3 text-center" >
                <input type="text" class="text-center form-control input-normal" required="true"  name="port" placeholder="Porta"/>
            </div>
            <div class="col-lg-3 text-center checkbox" >
               <label   >
                   <input type="checkbox" name="ssl">
                   SSL
               </label>
            </div>
            <div class="col-lg-12 text-center">
                <br>
                <label class="col-xs-5 control-label">Tipo do Servidor de Email</label>
                <div class="col-xs-7 selectContainer">
                    <select class="form-control" name="type">
                        <option value="gmail">Gmail</option>
                        <option value="collabserv">Collabserv</option>
                        <option value="qmail">Qmail</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-sm-12"><br>
        <input type = "submit" class="btn btn-info btn-md center-block" value = "Adicionar" />
        </div>
    </form>

</div>

</body>
</html>

app/templates/Index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ STATIC_URL }}/static/img/logo.png" />
    <title>LB2 Email Migration</title>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/jquery-3.1.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/bootstrap.min.js"></script>
    <link href="{{ STATIC_URL }}/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('main.index')}}">LB2 - Email Migration</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.migrations')}}">Configurar Migração</a></li>
            <li><a href="{{ url_for('main.create_client')}}">Adicionar Cliente</a></li>
            <li><a href="{{ url_for('main.create_server')}}">Adicionar Servidor</a></li>
        </ul>
    </div>
</nav>
<br>
<div class="flashes">
    {% for message in get_flashed_messages()%}
        <h4 class="form-text text-muted text-danger text-center">{{ message }}</h4>
    {% endfor %}
</div>
<div class="center-block text-center">
<img src="{{ STATIC_URL }}/static/img/complete_logo.png" style="position: absolute;
    margin: auto;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0">
</div>
</body>
</html>

app/templates/Migrations.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ STATIC_URL }}/static/img/logo.png" />
    <title>LB2 Email Migration</title>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/jquery-3.1.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}/static/js/bootstrap.min.js"></script>
    <link href="{{ STATIC_URL }}/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('main.index')}}">LB2 - Email Migration</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.migrations')}}">Configurar Migração</a></li>
            <li><a href="{{ url_for('main.create_client')}}">Adicionar Cliente</a></li>
            <li><a href="{{ url_for('main.create_server')}}">Adicionar Servidor</a></li>        </ul>
    </div>
</nav>
<br>
<div class="flashes">
    {% for message in get_flashed_messages()%}
        <h4 class="form-text text-muted text-danger text-center">{{ message }}</h4>
    {% endfor %}
</div>

<div class="col-sm-offset-1 text-info"><h4>Criar Nova Migração</h4></div>
<div class="col-sm-12 col-sm-offset-2 " >
    <form class="form-inline" action = "{{ request.path }}" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label>Cliente:</label>
            <select required="true" class="form-control input-large" name="company">
                    {% for c in clientes %}
                        <option value="{{ c.id }}">{{ c.name }}</option>
                    {% endfor %}
            </select>
            <input type = "submit" class="btn btn-info btn-md" value = "Criar" />
        </div>



    </form>
</div>

{% if existing_migrations %}
<br><br>
<div class="col-sm-offset-1 text-info"><h4>Migrações Existentes</h4></div>
    <div class="table-responsive col-sm-offset-1 col-sm-10">
        <table class="table table-striped table-bordered table-hover">
            <thead class="text-warning">
            <th class="text-center">ID</th>
            <th class="text-center">Cliente</th>
            <th class="text-center">Inicio</th>
            <th class="text-center">Fim</th>
            <th class="text-center">Configurar</th>
            </thead>
            <tbody>
            {% for migration in existing_migrations %}
                <tr>
                    <td class="text-center">{{ migration.id }}</td>
                    <td class="text-center">{{ company.query.filter_by(id=migration.company_id).first().name }}</td>
                    <td class="text-center">{{ migration.start_date }}</td>
                    <td class="text-center">{{ migration.end_date }}</td>
                    <td class="text-center">
                        <form action = "config/{{ migration.id }}" method="get">
                            <input type = "submit"  class="btn btn-info" value = "Configurar" />
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endif %}

</body>
</html>